version: "3.9"
networks:
  projectnet:
    driver: bridge
services:
  frontend:
    container_name: project-frontend
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    environment:
      - API_ENDPOINT=http://backend:8000
    networks:
      - projectnet
  backend:
    container_name: project-backend
    ports:
      - 8000:8000
    build: backend
    networks:
      - projectnet
    volumes:
      - ./backend:/code
      - ./backend/models:/models
    command: bash -c "ls & uvicorn api:app --host 0.0.0.0 --port 8000 --reload"
