version: "3.9"
networks:
  projectnet:
    driver: bridge
services:
  frontend:
    platform: linux/amd64
    container_name: project-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 8501:80
    depends_on:
      - backend
    environment:
      - API_ENDPOINT=http://backend
    volumes:
      - ${PWD}/frontend:/app
    networks:
      - projectnet
  backend:
    platform: linux/amd64
    container_name: project-backend
    ports:
      - 8000:80
    build:
      context: backend
      dockerfile: Dockerfile.prod
    volumes:
      - ${PWD}/backend:/app
    networks:
      - projectnet
