version: "3.9"
networks:
  demonet:
    driver: bridge
services:
  db:
    container_name: docker-demo.postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demodb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    networks:
      - demonet
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: docker-demo/api
#    container_name: docker-demo.api
#    environment:
#      - DATABASE_URL=postgresql://postgres:postgres@db:5432/demodb
#      - GOOGLE_APPLICATION_CREDENTIALS=/opt/service-account.json
#      - GCP_BUCKET_NAME=uao-coure-images
#    ports:
#      - "8000:8000"
#    command: bash -c "ls & uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
#    volumes:
#      - ./:/code
#      - ./data:/data
#    depends_on:
#      - db
#    networks:
#      - demonet
  pgadmin:
    container_name: docker-demo.pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
        - demonet
    logging:
      driver: none
